# fly.toml app configuration file generated for google-maps-sync on 2025-02-28T13:14:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'google-maps-sync'
primary_region = 'arn'

[build]
  [build.args]
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = ""

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
